# NginxFlow 主配置
# 说明：NginxFlow 管理后台由 Go 二进制直接提供，nginx 仅负责管理转发规则
load_module /usr/lib/nginx/modules/ngx_stream_module.so;

user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;
    client_max_body_size 64m;
    log_format combined_custom '$remote_addr - [$time_local] "$request" '
                               '$status $body_bytes_sent "$http_referer" "$http_user_agent"';

    include /etc/nginx/conf.d/*-http.conf;
}

stream {
    log_format basic '$remote_addr [$time_local] '
                     '$protocol $status $bytes_sent $bytes_received '
                     '$session_time "$upstream_addr"';
    include /etc/nginx/conf.d/*-stream.conf;
}
